/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iesiliberis.crudcentroeducativo.formularios;


import com.iesiliberis.crudcentroeducativo.ControladorDAO.alumnoDaoImp;
import com.iesiliberis.crudcentroeducativo.ControladorDAO.personalDaoImp;
import com.iesiliberis.crudcentroeducativo.entidades.alumno;
import com.iesiliberis.crudcentroeducativo.entidades.personal;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Raúl
 */
public class fmalumno extends javax.swing.JFrame {

    /**
     * Creates new form fmalumno
     */
    public fmalumno() throws SQLException {
        initComponents();
        configtabla();
        cargatabla();
    }

    private void configtabla(){
        String col[]={"ID","DNI","NOMBRE","APELLIDO1","APELLIDO2","FECHA NACIMIENTO","TELEFONO","EMAIL","DIRECCION","CP","POBLACION","PROVINCIA"};
        jtalumno.getModel();
        DefaultTableModel mode = new DefaultTableModel(col,0){
                @Override
                public boolean isCellEditable(int row,int column){
                    return false;
                }
        };
        jtalumno.setModel(mode);
        
        
            
        
    }
    
    private void cargatabla() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel)jtalumno.getModel();
        modelo.setNumRows(0);
        
        alumnoDaoImp al=alumnoDaoImp.getInstance();
        List<alumno> alumnos=al.getAll();
        String [] fila =new String[12];
        for (alumno alum:alumnos){
            fila[0]=""+alum.getId();
            fila[1]=""+alum.getDni();
            fila[2]=""+alum.getNombre();
            fila[3]=""+alum.getApellido1();
            fila[4]=""+alum.getApellido2();
            fila[5]=""+alum.getfNacimiento();
            fila[6]=""+alum.getTelefono();
            fila[7]=""+alum.getEmail();
            fila[8]=""+alum.getDireccion();
            fila[9]=""+alum.getCp();
            fila[10]=""+alum.getPoblacion();
            fila[11]=""+alum.getProvincia();
            modelo.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtdni = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtape1 = new javax.swing.JTextField();
        txtape2 = new javax.swing.JTextField();
        txtfNac = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtdir = new javax.swing.JTextField();
        txtcp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpob = new javax.swing.JTextField();
        txtprov = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtalumno = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, -1));

        jLabel1.setText("Buscar por nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        jButton4.setText("Editar Autorizados");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));
        jPanel1.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, -1));
        jPanel1.add(txtape1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 80, -1));
        jPanel1.add(txtape2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 80, -1));

        txtfNac.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtfNac.setText("AAAA-MM-DD");
        jPanel1.add(txtfNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 80, -1));
        jPanel1.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 80, -1));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 80, -1));
        jPanel1.add(txtdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 80, -1));
        jPanel1.add(txtcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));

        jLabel2.setText("DNI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel4.setText("APELLIDO1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel5.setText("APELLIDO2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel6.setText("fNacimiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel7.setText("Telefono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jLabel9.setText("Direccion");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jLabel10.setText("CP");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(txtpob, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 90, -1));
        jPanel1.add(txtprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 90, -1));

        jLabel13.setText("Poblacion");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel14.setText("Provincia");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 740, 240));

        jtalumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtalumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtalumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtalumno);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            DefaultTableModel modelo = (DefaultTableModel) jtalumno.getModel();
            TableRowSorter<TableModel> trsorter= new TableRowSorter(modelo);
            jtalumno.setRowSorter(trsorter);
            if (txtbuscar.getText().length()==0){
                trsorter.setRowFilter(null);
            }else{
                trsorter.setRowFilter(RowFilter.regexFilter(txtbuscar.getText().trim()));
            }
            
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void jtalumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtalumnoMouseClicked
        int fila = jtalumno.getSelectedRow();
        txtdni.setText(String.valueOf(jtalumno.getValueAt(fila, 1)));
        txtnombre.setText(String.valueOf(jtalumno.getValueAt(fila, 2)));
        txtape2.setText(String.valueOf(jtalumno.getValueAt(fila, 4)));
        txtape1.setText(String.valueOf(jtalumno.getValueAt(fila, 3)));
        txtfNac.setText(String.valueOf(jtalumno.getValueAt(fila, 5)));
        txtdir.setText(String.valueOf(jtalumno.getValueAt(fila, 8)));
        txtcp.setText(String.valueOf(jtalumno.getValueAt(fila, 9)));
        txtpob.setText(String.valueOf(jtalumno.getValueAt(fila, 10)));
        txtprov.setText(String.valueOf(jtalumno.getValueAt(fila, 11)));
        txttel.setText(String.valueOf(jtalumno.getValueAt(fila, 6)));
        txtemail.setText(String.valueOf(jtalumno.getValueAt(fila, 7)));
        
        if (evt.getClickCount()==2){
            JDialog frame=new JDialog(this,"Detalle Alumno",true);
            jpAlumnoDetalle panel=new jpAlumnoDetalle();
            int idseleccion=Integer.parseInt(jtalumno.getValueAt(jtalumno.getSelectedRow(), 0).toString());
            panel.CargaDetalle(idseleccion);
            frame.getContentPane().add(panel);
            frame.pack();
            frame.setVisible(true);
        }
    }//GEN-LAST:event_jtalumnoMouseClicked

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int fila = jtalumno.getSelectedRow();
        String id = String.valueOf(jtalumno.getValueAt(fila, 0));
        alumnoDaoImp alu=alumnoDaoImp.getInstance();
        try {
            alu.delete(Integer.parseInt(id));
            cargatabla();
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getMessage());;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        alumnoDaoImp alu=alumnoDaoImp.getInstance();
        int telefono=Integer.parseInt(txttel.getText());
        alumno alum = new alumno(txtnombre.getText(),txtape1.getText(),txtape2.getText(),telefono,txtemail.getText(),txtdni.getText(),txtdir.getText(),txtpob.getText(),txtprov.getText(),txtcp.getText());
        alum.setfNacimiento(Date.valueOf(txtfNac.getText()));
        
        try {
            if (txtdni.getText().equals("")&& txtfNac.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Introduzca como minimo un DNI y una Fecha de nacimiento");
            }
            else {
            alu.add(alum);
            cargatabla();
            txtdni.setText("");
            txtnombre.setText("");
            txtape1.setText("");
            txtape2.setText("");
            txtfNac.setText("AAAA-MM-DD");
            txtdir.setText("");
            txtcp.setText("");
            txtpob.setText("");
            txtprov.setText("");
            txttel.setText("");
            txtemail.setText("");
            }
            
        } catch (SQLException ex) {
            System.out.println("error" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        alumnoDaoImp alu=alumnoDaoImp.getInstance();
        int id=Integer.parseInt(String.valueOf(jtalumno.getValueAt(jtalumno.getSelectedRow(), 0)));
        int telefono=Integer.parseInt(txttel.getText());
        alumno alum = new alumno(id,txtnombre.getText(),txtape1.getText(),txtape2.getText(),Date.valueOf(txtfNac.getText()),telefono,txtemail.getText(),txtdni.getText(),txtdir.getText(),txtpob.getText(),txtprov.getText(),txtcp.getText());
        
        try {
            if (txtdni.getText().equals("")&& txtfNac.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Introduzca como minimo un DNI y una Fecha de nacimiento");
            }
            else {
            alu.update(alum);
            cargatabla();
            txtdni.setText("");
            txtnombre.setText("");
            txtape1.setText("");
            txtape2.setText("");
            txtfNac.setText("AAAA-MM-DD");
            txtdir.setText("");
            txtcp.setText("");
            txtpob.setText("");
            txtprov.setText("");
            txttel.setText("");
            txtemail.setText("");
            }
            
        } catch (SQLException ex) {
            System.out.println("error" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int fila = jtalumno.getSelectedRow();
        String id = String.valueOf(jtalumno.getValueAt(fila, 0));
        if (id.equals("")){
            JOptionPane.showMessageDialog(this,"SELECCIONE UN ALUMNO");
        }
        else {
            frmAutorizados autorizados;
            try {
                autorizados = new frmAutorizados(Integer.parseInt(id));
                autorizados.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(fmalumno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmalumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmalumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmalumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmalumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fmalumno().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fmalumno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtalumno;
    private javax.swing.JTextField txtape1;
    private javax.swing.JTextField txtape2;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcp;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfNac;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpob;
    private javax.swing.JTextField txtprov;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
