/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iesiliberis.crudcentroeducativo.formularios;

import com.iesiliberis.crudcentroeducativo.ControladorDAO.alumnoDaoImp;
import com.iesiliberis.crudcentroeducativo.ControladorDAO.autorizadoDaoImp;
import com.iesiliberis.crudcentroeducativo.entidades.autorizado;
import com.iesiliberis.crudcentroeducativo.entidades.parentesco;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raúl
 */
public class frmAutorizados extends javax.swing.JFrame {
    int idAlumno;
    boolean tut1,tut2;
    /**
     * Creates new form frmAutorizados
     */
    public frmAutorizados(int id) throws SQLException {
        initComponents();
        configtabla();
        tut1=false;
        tut2=false;
        idAlumno=id;
        cargatabla();
    }

    public frmAutorizados() {
    }
      private void configtabla(){
        String col[]={"ID","DNI","NOMBRE","APELLIDO1","APELLIDO2","PARENTESCO"};
        jtAutorizados.getModel();
        DefaultTableModel mode = new DefaultTableModel(col,0){
                @Override
                public boolean isCellEditable(int row,int column){
                    return false;
                }
        };
        jtAutorizados.setModel(mode);
      }
        private void cargatabla() throws SQLException{
              tut1=false;
              tut2=false;
        DefaultTableModel modelo = (DefaultTableModel)jtAutorizados.getModel();
        modelo.setNumRows(0);
        
        alumnoDaoImp aut=alumnoDaoImp.getInstance();
        List<autorizado> auto =aut.getautorizados(idAlumno);
        String [] fila = new String [6];
            for (autorizado au:auto){
                fila[0]=""+String.valueOf(au.getId());
                fila[1]=""+au.getDni();
                fila[2]=""+au.getNombre();
                fila[3]=""+au.getApellido1();
                fila[4]=""+au.getApellido2();
                if (String.valueOf(au.getParent()).equals("TUTOR1")){
                    tut1=true;
                }
                if (String.valueOf(au.getParent()).equals("TUTOR2")){
                    tut2=true;
                }
                
                fila[5]=""+au.getParent();
                modelo.addRow(fila);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAutorizados = new javax.swing.JTable();
        txtdni = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido1 = new javax.swing.JTextField();
        txtapellido2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbParentesco = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtAutorizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtAutorizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAutorizadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAutorizados);

        jLabel1.setText("DNI");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("APELLIDO1");

        jLabel4.setText("APELLIDO2");

        jLabel5.setText("PARENTESCO");

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbParentesco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TUTOR1", "TUTOR2", "OTRO" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtapellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        autorizadoDaoImp auto=autorizadoDaoImp.getInstance();
        autorizado aut=null;
        if (cbParentesco.getSelectedItem().equals("TUTOR1") && tut1 ||cbParentesco.getSelectedItem().equals("TUTOR2") && tut2){
            JOptionPane.showMessageDialog(this,"EL TUTOR INTRODUCIDO YA EXISTE");
            try {
                cargatabla();
            } catch (SQLException ex) {
                Logger.getLogger(frmAutorizados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            if (cbParentesco.getSelectedItem().equals("TUTOR1")){
            aut= new autorizado(txtdni.getText(),txtnombre.getText(),txtapellido1.getText(),txtapellido2.getText(),parentesco.TUTOR1);
        }
        if (cbParentesco.getSelectedItem().equals("TUTOR2")){
           aut= new autorizado(txtdni.getText(),txtnombre.getText(),txtapellido1.getText(),txtapellido2.getText(),parentesco.TUTOR2);
        }
        if (cbParentesco.getSelectedItem().equals("OTROS")){
            aut = new autorizado(txtdni.getText(),txtnombre.getText(),txtapellido1.getText(),txtapellido2.getText(),parentesco.OTROS);
        }
        
        try {
            if (txtdni.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Introduzca como minimo un DNI");
            }
            else {
            auto.add(aut);
            cargatabla();
            txtdni.setText("");
            txtnombre.setText("");
            txtapellido1.setText("");
            txtapellido2.setText("");
            }
            
        } catch (SQLException ex) {
            System.out.println("error" + ex.getMessage());
        }
        autorizado autor=auto.devolvAutorizadodni(aut.getDni());
        auto.addautorizado(idAlumno, autor.getId());
            try {
                cargatabla();
            } catch (SQLException ex) {
                Logger.getLogger(frmAutorizados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtAutorizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAutorizadosMouseClicked
        int fila = jtAutorizados.getSelectedRow();
        txtdni.setText(String.valueOf(jtAutorizados.getValueAt(fila, 1)));
        txtnombre.setText(String.valueOf(jtAutorizados.getValueAt(fila, 2)));
        txtapellido1.setText(String.valueOf(jtAutorizados.getValueAt(fila, 3)));
        txtapellido2.setText(String.valueOf(jtAutorizados.getValueAt(fila, 4)));
        if (jtAutorizados.getValueAt(fila, 5).equals("TUTOR1")){
            cbParentesco.setSelectedItem("TUTOR1");
        }
        if (jtAutorizados.getValueAt(fila, 5).equals("TUTOR2")){
           cbParentesco.setSelectedItem("TUTOR2");
        }
        if (jtAutorizados.getValueAt(fila, 5).equals("OTROS")){
            cbParentesco.setSelectedItem("OTROS");

        }
    }//GEN-LAST:event_jtAutorizadosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        alumnoDaoImp alu=alumnoDaoImp.getInstance();
        int id=Integer.parseInt(String.valueOf(jtAutorizados.getValueAt(jtAutorizados.getSelectedRow(), 0)));
        autorizadoDaoImp auto=autorizadoDaoImp.getInstance();
        autorizado aut=null;
            if (cbParentesco.getSelectedItem().equals("TUTOR1")){
            aut= new autorizado(id,txtdni.getText(),txtnombre.getText(),txtapellido1.getText(),txtapellido2.getText(),parentesco.TUTOR1);
        }
        if (cbParentesco.getSelectedItem().equals("TUTOR2")){
           aut= new autorizado(id,txtdni.getText(),txtnombre.getText(),txtapellido1.getText(),txtapellido2.getText(),parentesco.TUTOR2);
        }
        if (cbParentesco.getSelectedItem().equals("OTROS")){
            aut = new autorizado(id,txtdni.getText(),txtnombre.getText(),txtapellido1.getText(),txtapellido2.getText(),parentesco.OTROS);
        }
        
        try {
            if (txtdni.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Introduzca como minimo un DNI");
            }
            else {
            auto.update(aut);
            cargatabla();
            txtdni.setText("");
            txtnombre.setText("");
            txtapellido1.setText("");
            txtapellido2.setText("");
            }
            
        } catch (SQLException ex) {
            System.out.println("error" + ex.getMessage());
        }
            try {
                cargatabla();
            } catch (SQLException ex) {
                Logger.getLogger(frmAutorizados.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int fila = jtAutorizados.getSelectedRow();
        String id = String.valueOf(jtAutorizados.getValueAt(fila, 0));
        autorizadoDaoImp autor=autorizadoDaoImp.getInstance();
        try {
            autor.delete(Integer.parseInt(id));
            cargatabla();
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAutorizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAutorizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAutorizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAutorizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAutorizados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbParentesco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtAutorizados;
    private javax.swing.JTextField txtapellido1;
    private javax.swing.JTextField txtapellido2;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
