/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iesiliberis.crudcentroeducativo.formularios;

import com.iesiliberis.crudcentroeducativo.ControladorDAO.CursoAcademicoDaoImp;
import com.iesiliberis.crudcentroeducativo.ControladorDAO.CursoDaoImp;
import com.iesiliberis.crudcentroeducativo.entidades.curso;
import com.iesiliberis.crudcentroeducativo.entidades.cursoacademico;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raúl
 */
public class FrmCursos extends javax.swing.JFrame {

    /**
     * Creates new form frmCursoAcademico
     */
    public FrmCursos() throws SQLException {
        initComponents();
        configjcombobox();
        configtabla(); 
        cargatabla();
        txtidcurso.setVisible(false);

    }
    private void configjcombobox() throws SQLException{
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        List<cursoacademico> cursos;
        CursoAcademicoDaoImp curs=CursoAcademicoDaoImp.getInstance();
        cursos = curs.getAll();
        for (cursoacademico cur:cursos){
            modelo.addElement(cur.getDescripcion());
        }
        jComboBox1.setModel(modelo);
    }
    private void configtabla(){
        String col[]={"ID","COD","NOMBRE","OBSERVACIONES","CURSOACADEMICO"};
        jtabcursos.getModel();
        DefaultTableModel mode = new DefaultTableModel(col,0){
                @Override
                public boolean isCellEditable(int row,int column){
                    return false;
                }
        };
        jtabcursos.setModel(mode);
        
        
        
    }
    
    private void cargatabla() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel)jtabcursos.getModel();
        modelo.setNumRows(0);
        
        CursoDaoImp curs=CursoDaoImp.getInstance();
        CursoAcademicoDaoImp cursaca=CursoAcademicoDaoImp.getInstance();
        List<curso> cursos;
        List<cursoacademico> cursosaca;
        cursosaca=cursaca.getAll();
        for (cursoacademico curso:cursosaca){
            if (curso.getDescripcion().equals(jComboBox1.getSelectedItem())){
            cursos = curs.getAllByCursoAcademico(curso.getId());
            String [] fila =new String[5];
        
            for (curso cur:cursos){
                fila[0]=""+String.valueOf(cur.getId());
                fila[1]=""+cur.getCodigo();
                fila[2]=""+cur.getNombre();
                fila[3]=""+cur.getObservaciones();
                fila[4]=""+curso.getDescripcion();
                modelo.addRow(fila);
            }
            txtcursoaca.setText(curso.getDescripcion());
            txtidcurso.setText(String.valueOf(curso.getId()));
            }
        
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabcursos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtyearinicio = new javax.swing.JTextField();
        txtyearfin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_descrip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtcursoaca = new javax.swing.JTextField();
        txtidcurso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtabcursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "COD", "NOMBRE", "OBSERVACIONES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtabcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabcursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabcursos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("COD");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jPanel3.add(txtyearinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, -1));
        jPanel3.add(txtyearfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, -1));

        jLabel2.setText("NOMBRE");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        txt_descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripActionPerformed(evt);
            }
        });
        jPanel3.add(txt_descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 310, -1));

        jLabel3.setText("OBSERVACIONES");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        btnAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raúl\\Desktop\\Programacion\\Ejemplos de clase programacion\\CRUDCentroEducativo\\src\\main\\java\\com\\iesiliberis\\crudcentroeducativo\\add_box_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        btnActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raúl\\Desktop\\Programacion\\Ejemplos de clase programacion\\CRUDCentroEducativo\\src\\main\\java\\com\\iesiliberis\\crudcentroeducativo\\done_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        btnBorrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raúl\\Desktop\\Programacion\\Ejemplos de clase programacion\\CRUDCentroEducativo\\src\\main\\java\\com\\iesiliberis\\crudcentroeducativo\\backspace_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        btnBorrar.setToolTipText("");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel4.setText("CURSOACADEMICO");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));
        jPanel3.add(txtcursoaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 120, -1));

        txtidcurso.setText("jTextField1");
        jPanel3.add(txtidcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel5.setText("Doble click para seleccionar:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        CursoDaoImp curs=CursoDaoImp.getInstance();
        curso cur= new curso(txtyearinicio.getText(),txtyearfin.getText(),txt_descrip.getText(),Integer.parseInt(txtidcurso.getText()));
        
        try {
            if (txtyearinicio.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Introduzca como minimo un codigo de curso");
            }
            else {
            curs.add(cur);
            cargatabla();
            txtyearinicio.setText("");
            txtyearfin.setText("");
            txt_descrip.setText("");
            }
            
        } catch (SQLException ex) {
            System.out.println("error" + ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txt_descripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = jtabcursos.getSelectedRow();
        String id=String.valueOf(jtabcursos.getValueAt(fila, 0));
        CursoDaoImp curs=CursoDaoImp.getInstance();
        
        curso cur= new curso(Integer.parseInt(id),txtyearinicio.getText(),txtyearfin.getText(),txt_descrip.getText(),Integer.parseInt(txtidcurso.getText()));
        try {
            curs.update(cur);
            cargatabla();
            txtyearinicio.setText("");
            txtyearfin.setText("");
            txt_descrip.setText("");
        } catch (SQLException ex) {
            System.out.println("error" + ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jtabcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabcursosMouseClicked
        int fila = jtabcursos.getSelectedRow();
        txtyearinicio.setText(String.valueOf(jtabcursos.getValueAt(fila, 1)));
        txtyearfin.setText(String.valueOf(jtabcursos.getValueAt(fila, 2)));
        txt_descrip.setText(String.valueOf(jtabcursos.getValueAt(fila, 3)));
        txtcursoaca.setText(String.valueOf(jtabcursos.getValueAt(fila, 4)));
        if (evt.getClickCount()==2){
            
            int idseleccion=Integer.parseInt(jtabcursos.getValueAt(jtabcursos.getSelectedRow(), 0).toString());
            frmUnidad unidad;
            try {
                unidad = new frmUnidad(idseleccion);
                unidad.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(FrmCursos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jtabcursosMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila = jtabcursos.getSelectedRow();
        String id = String.valueOf(jtabcursos.getValueAt(fila, 0));
        CursoDaoImp curs=CursoDaoImp.getInstance();
        try {
            curs.delete(Integer.parseInt(id));
            cargatabla();
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getMessage());;
        }
        
                
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        try {
            cargatabla();
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmCursos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmCursos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmCursos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabcursos;
    private javax.swing.JTextField txt_descrip;
    private javax.swing.JTextField txtcursoaca;
    private javax.swing.JTextField txtidcurso;
    private javax.swing.JTextField txtyearfin;
    private javax.swing.JTextField txtyearinicio;
    // End of variables declaration//GEN-END:variables
}
