/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iesiliberis.crudcentroeducativo.formularios;

import com.iesiliberis.crudcentroeducativo.ControladorDAO.alumnoDaoImp;
import com.iesiliberis.crudcentroeducativo.ControladorDAO.matriculaDaoImp;
import com.iesiliberis.crudcentroeducativo.entidades.alumno;
import com.iesiliberis.crudcentroeducativo.entidades.matricula;
import java.sql.Date;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raúl
 */
public class frmMatriculas extends javax.swing.JFrame {
    int idunidad;
    /**
     * Creates new form frmMatriculas
     */
    public frmMatriculas(int id) throws SQLException {
        initComponents();
        idunidad=id;
        configtabla1();
        configtabla2();
        cargatabla();
        cargatabla2();
    }

    public frmMatriculas() {
    }
    
    private void configtabla1(){
        String col[]={"ID","DNI","NOMBRE","APELLIDO1","APELLIDO2","FECHA NACIMIENTO","TELEFONO","EMAIL","DIRECCION","CP","POBLACION","PROVINCIA"};
        jtalumno.getModel();
        DefaultTableModel mode = new DefaultTableModel(col,0){
                @Override
                public boolean isCellEditable(int row,int column){
                    return false;
                }
        };
        jtalumno.setModel(mode);
    }
    private void configtabla2(){
        String col[]={"ID","DNI","NOMBRE","APELLIDO1","APELLIDO2","FECHA NACIMIENTO","TELEFONO","EMAIL","DIRECCION","CP","POBLACION","PROVINCIA","FECHA MATRICULA","DESCRIPCION"};
        jtMatriculado.getModel();
        DefaultTableModel mode = new DefaultTableModel(col,0){
                @Override
                public boolean isCellEditable(int row,int column){
                    return false;
                }
        };
        jtMatriculado.setModel(mode);
    }
        private void cargatabla() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel)jtalumno.getModel();
        modelo.setNumRows(0);
        
        alumnoDaoImp al=alumnoDaoImp.getInstance();
        List<alumno> alumnos=al.getalumnosnotincurso(idunidad);
        String [] fila =new String[12];
        for (alumno alum:alumnos){
            fila[0]=""+alum.getId();
            fila[1]=""+alum.getDni();
            fila[2]=""+alum.getNombre();
            fila[3]=""+alum.getApellido1();
            fila[4]=""+alum.getApellido2();
            fila[5]=""+alum.getfNacimiento();
            fila[6]=""+alum.getTelefono();
            fila[7]=""+alum.getEmail();
            fila[8]=""+alum.getDireccion();
            fila[9]=""+alum.getCp();
            fila[10]=""+alum.getPoblacion();
            fila[11]=""+alum.getProvincia();
            modelo.addRow(fila);
        }
    }
        private void cargatabla2() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel)jtMatriculado.getModel();
        modelo.setNumRows(0);
        
        
        alumnoDaoImp al=alumnoDaoImp.getInstance();
        List<alumno> alumnos=al.getalumnoscurso(idunidad);
        String [] fila =new String[14];
        for (alumno alum:alumnos){
            fila[0]=""+alum.getId();
            fila[1]=""+alum.getDni();
            fila[2]=""+alum.getNombre();
            fila[3]=""+alum.getApellido1();
            fila[4]=""+alum.getApellido2();
            fila[5]=""+alum.getfNacimiento();
            fila[6]=""+alum.getTelefono();
            fila[7]=""+alum.getEmail();
            fila[8]=""+alum.getDireccion();
            fila[9]=""+alum.getCp();
            fila[10]=""+alum.getPoblacion();
            fila[11]=""+alum.getProvincia();
            matriculaDaoImp mat = matriculaDaoImp.getInstance();
            matricula matr=mat.getbyAlumnoycurso(alum.getId(), idunidad);
            fila[12]=""+matr.getfMatricula();
            fila[13]=""+matr.getDescripcion();
            modelo.addRow(fila);
        }
    }
        
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtalumno = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMatriculado = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtfMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtalumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtalumno);

        jtMatriculado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMatriculado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMatriculadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtMatriculado);

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("MATRICULADOS");

        jLabel2.setText("ALUMNOS");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        jLabel3.setText("DESCRIPCION");

        jLabel4.setText("Fecha Matricula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addContainerGap(563, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int fila= jtalumno.getSelectedRow();
        matriculaDaoImp matr = matriculaDaoImp.getInstance();
        matricula mat=null;
        if (txtDescripcion.getText().equals("")){
            mat= new matricula(Integer.parseInt(String.valueOf(jtalumno.getValueAt(fila,0))),idunidad,String.valueOf(jtalumno.getValueAt(fila,3)),Date.valueOf(LocalDate.now()));
        }
        else{
            mat= new matricula(Integer.parseInt(String.valueOf(jtalumno.getValueAt(fila,0))),idunidad,txtDescripcion.getText(),Date.valueOf(txtfMatricula.getText()));
        }
        
        try {
            matr.add(mat);
            cargatabla();
            cargatabla2();
        } catch (SQLException ex) {
            Logger.getLogger(frmMatriculas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int fila= jtMatriculado.getSelectedRow();
        matriculaDaoImp matr = matriculaDaoImp.getInstance();
        matricula id=null;
        try {
            id = matr.getbyAlumnoycurso(Integer.parseInt(String.valueOf(jtMatriculado.getValueAt(fila,0))), idunidad);
        } catch (SQLException ex) {
            Logger.getLogger(frmMatriculas.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(LocalDate.now());
        matricula mat= new matricula(id.getId(),Integer.parseInt(String.valueOf(jtMatriculado.getValueAt(fila,0))),idunidad,txtDescripcion.getText(),Date.valueOf(txtfMatricula.getText()),Date.valueOf(LocalDate.now()));
        try {
            matr.update(mat);
            cargatabla();
            cargatabla2();
        } catch (SQLException ex) {
            Logger.getLogger(frmMatriculas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtMatriculadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMatriculadoMouseClicked
        int fila=jtMatriculado.getSelectedRow();
        txtDescripcion.setText(String.valueOf(jtMatriculado.getValueAt(fila, 13)));
        txtfMatricula.setText(String.valueOf(jtMatriculado.getValueAt(fila, 12)));
    }//GEN-LAST:event_jtMatriculadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMatriculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtMatriculado;
    private javax.swing.JTable jtalumno;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtfMatricula;
    // End of variables declaration//GEN-END:variables
}
